"""Migration 023: OSCA 2024 occupation backbone (FR-9.1, Phase A).

Introduces the Australian Occupation Standard Classification (OSCA 2024 v1.0,
ABS) as the canonical AU occupation entity, replacing the retired ANZSCO as the
*backbone* while retaining ANZSCO as a legacy key (dual-key transition).

Non-breaking by design:
  - Four new OSCA tables (occupations, main tasks, ANZSCO/ISCO correspondences).
  - Nullable ``osca_code`` added to ``abs_employment`` and
    ``industry_occupation_profiles``. Existing rows are untouched; the region
    mechanics and ANZSCO keys stay exactly as they are.

Backfill is deliberately NOT performed here. ``abs_employment`` maps cleanly to
OSCA via ``osca_anzsco_map`` (it carries ``anzsco_code``), but
``industry_occupation_profiles`` is SOC-keyed with no ANZSCO column — populating
its ``osca_code`` requires the ``onet_soc -> anzsco -> osca`` chain WITH
employment apportionment for many-to-many correspondences. That logic lives in
the OSCA ingest / AU-profile compute step (app/services/industry_profiles.py),
not in a schema migration, so it can apportion split correspondences correctly
rather than double-count.

OSCA main tasks are GenAI-generated by ABS, few and broad, and have no O*NET/DWA
linkage — they are ``descriptor_only`` and carry exposure only at occupation
level. The task-level exposure carrier is the ASC specialist task (migration
024, FR-9.2). See ADR "AU task-level AI-exposure via a DWA-pivot decision
ladder" and docs/domain-model.md § "AU task-level crosswalk & confidence".

Source: ABS Occupation Standard Classification for Australia (OSCA) 2024 v1.0
        (released 6 Dec 2024) + OSCA<->ANZSCO and OSCA<->ISCO-08 correspondences.
"""

from alembic import op
import sqlalchemy as sa

revision = "023"
down_revision = "022"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── 1. OSCA occupation backbone ──
    op.create_table(
        "osca_occupations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("osca_code", sa.Text(), nullable=False),  # canonical 6-digit AU key
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("isco08_code", sa.Text(), nullable=True),
        sa.Column("unit_group", sa.Text(), nullable=True),  # OSCA hierarchy parent
        sa.Column("osca_version", sa.Text(), nullable=False, server_default="2024.1.0"),
        sa.Column("integrity_hash", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("osca_code", "osca_version"),
    )
    op.create_index("ix_osca_occupations_code", "osca_occupations", ["osca_code"])
    op.create_index("ix_osca_occupations_isco", "osca_occupations", ["isco08_code"])

    # ── 2. OSCA main tasks (descriptor-only; never an exposure carrier) ──
    op.create_table(
        "osca_main_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("osca_code", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=True),  # source task id if present
        sa.Column("task_text", sa.Text(), nullable=False),
        sa.Column("descriptor_only", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("osca_version", sa.Text(), nullable=False, server_default="2024.1.0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_osca_main_tasks_code", "osca_main_tasks", ["osca_code"])

    # ── 3. OSCA <-> ANZSCO correspondence (dual-key bridge) ──
    # relation_type / weight preserve many-to-many splits explicitly so downstream
    # employment apportionment never collapses them silently.
    op.create_table(
        "osca_anzsco_map",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("osca_code", sa.Text(), nullable=False),
        sa.Column("anzsco_code", sa.Text(), nullable=False),
        sa.Column("correspondence_type", sa.Text(), nullable=True),  # exact|split|partial
        sa.Column("relation_type", sa.Text(), nullable=True),  # 1:1|1:n|n:1|n:m
        sa.Column("weight", sa.Float(), nullable=True),  # apportionment weight
        sa.Column("osca_version", sa.Text(), nullable=False, server_default="2024.1.0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("osca_code", "anzsco_code", "osca_version"),
    )
    op.create_index("ix_osca_anzsco_osca", "osca_anzsco_map", ["osca_code"])
    op.create_index("ix_osca_anzsco_anzsco", "osca_anzsco_map", ["anzsco_code"])

    # ── 4. OSCA <-> ISCO-08 correspondence (occupation-level pivot for gap-fill) ──
    op.create_table(
        "osca_isco_map",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("osca_code", sa.Text(), nullable=False),
        sa.Column("isco08_code", sa.Text(), nullable=False),
        sa.Column("correspondence_type", sa.Text(), nullable=True),
        sa.Column("relation_type", sa.Text(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("osca_version", sa.Text(), nullable=False, server_default="2024.1.0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("osca_code", "isco08_code", "osca_version"),
    )
    op.create_index("ix_osca_isco_osca", "osca_isco_map", ["osca_code"])
    op.create_index("ix_osca_isco_isco", "osca_isco_map", ["isco08_code"])

    # ── 5. Additive dual-key columns (nullable; no backfill — see docstring) ──
    op.add_column("abs_employment", sa.Column("osca_code", sa.Text(), nullable=True))
    op.create_index("ix_abs_employment_osca", "abs_employment", ["osca_code"])

    op.add_column("industry_occupation_profiles", sa.Column("osca_code", sa.Text(), nullable=True))
    op.create_index(
        "ix_industry_occupation_profiles_osca",
        "industry_occupation_profiles",
        ["osca_code"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_industry_occupation_profiles_osca",
        table_name="industry_occupation_profiles",
    )
    op.drop_column("industry_occupation_profiles", "osca_code")

    op.drop_index("ix_abs_employment_osca", table_name="abs_employment")
    op.drop_column("abs_employment", "osca_code")

    op.drop_table("osca_isco_map")
    op.drop_table("osca_anzsco_map")
    op.drop_table("osca_main_tasks")
    op.drop_table("osca_occupations")
